In [1]:
! pip3 install pandas

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Downloading pandas-2.3.3-cp39-cp39-macosx_11_0_arm64.whl (10.8 MB)
     |████████████████████████████████| 10.8 MB 1.4 MB/s eta 0:00:01
Collecting pytz>=2020.1
  Downloading pytz-2026.3.post1-py2.py3-none-any.whl (508 kB)
     |████████████████████████████████| 508 kB 11.9 MB/s eta 0:00:01
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/prachipradhan/Library/Python/3.9/lib/python/site-packages (from pandas) (2.9.0.post0)
Collecting tzdata>=2022.7
  Downloading tzdata-2026.3-py2.py3-none-any.whl (348 kB)
     |████████████████████████████████| 348 kB 18.5 MB/s eta 0:00:01
Requirement already satisfied: numpy>=1.22.4 in /Users/prachipradhan/Library/Python/3.9/lib/python/site-packages (from pandas) (2.0.2)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)
Installing collected packages: tzdata, pytz, pandas
Successfully installed pandas-2.3.3 pytz-2026.3.post1 tzdata-2026.3
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.

In [3]:
import pandas as pd 
import numpy as np

In [10]:
# pd.Series() - 1D data with an index

resturant_Data = {
    'Table_No' : [12,14,15],
    'Bill_Amount':[1250,890,2400],
    'Waiter_Name':['Amit','Priya','Rahul']
} 

df = pd.DataFrame(resturant_Data)

# print(df)

# Table_No  Bill_Amount Waiter_Name
# 0        12         1250        Amit
# 1        14          890       Priya
# 2        15         2400       Rahul


# print(type(df))
# <class 'pandas.core.frame.DataFrame'>


# print(df['Bill_Amount'])

# 0    1250
# 1     890
# 2    2400
# Name: Bill_Amount, dtype: int64


# print(type(df['Bill_Amount']))

# <class 'pandas.core.series.Series'>


#>>>>>>>> SERIES<<<<<<<<<#

total_bill = [4700,8000,1200,500]

s=pd.Series(total_bill,index=['mon','tue','wed','fri'])

print(s)
print(type(s))

mon    4700
tue    8000
wed    1200
fri     500
dtype: int64
<class 'pandas.core.series.Series'>

In [ ]:
#.values

print(df.values)
print(type(df.values))

[[12 1250 'Amit']
 [14 890 'Priya']
 [15 2400 'Rahul']]
<class 'numpy.ndarray'>

In [15]:
items = [45,30,15,60]

s=pd.Series(items,index=('Pizza','Burger','Pasta','Fries'))
print(s)

Pizza     45
Burger    30
Pasta     15
Fries     60
dtype: int64

In [ ]:
Stock_Data = {
    'Brand':['Nike','Puma','Adidas','rebook'],
    ''

}

In [8]:
import pandas as pd
import numpy as np
df=pd.read_csv("/Users/prachipradhan/Desktop/MACHINE_LEARNING/Pandas/tip.csv")
df.head(2)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3

In [9]:
df.tail(20)

     total_bill   tip     sex smoker   day    time  size
224       13.42  1.58    Male    Yes   Fri   Lunch     2
225       16.27  2.50  Female    Yes   Fri   Lunch     2
226       10.09  2.00  Female    Yes   Fri   Lunch     2
227       20.45  3.00    Male     No   Sat  Dinner     4
228       13.28  2.72    Male     No   Sat  Dinner     2
229       22.12  2.88  Female    Yes   Sat  Dinner     2
230       24.01  2.00    Male    Yes   Sat  Dinner     4
231       15.69  3.00    Male    Yes   Sat  Dinner     3
232       11.61  3.39    Male     No   Sat  Dinner     2
233       10.77  1.47    Male     No   Sat  Dinner     2
234       15.53  3.00    Male    Yes   Sat  Dinner     2
235       10.07  1.25    Male     No   Sat  Dinner     2
236       12.60  1.00    Male    Yes   Sat  Dinner     2
237       32.83  1.17    Male    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [11]:
df.sample(5)

     total_bill   tip     sex smoker   day    time  size
120       11.69  2.31    Male     No  Thur   Lunch     2
242       17.82  1.75    Male     No   Sat  Dinner     2
191       19.81  4.19  Female    Yes  Thur   Lunch     2
182       45.35  3.50    Male    Yes   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2

In [15]:
df.shape

#gives no of rows and colouns 

# df.columns

# df.columns[1]

df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [18]:
print(df['day'].value_counts())

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [19]:
print(df['day'].unique())

['Sun' 'Sat' 'Thur' 'Fri']

In [ ]:
print(df['day'].ununique())

# titanic dataset

AttributeError: 'Series' object has no attribute 'ununique'

In [2]:
import pandas as pd 
import numpy as np

df=pd.read_csv("/Users/prachipradhan/Desktop/MACHINE_LEARNING/Pandas/tip.csv")
df.head(2)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3

In [ ]:
x =df['day']

print(x.shape)

y = df['']
print(x)

0       Sun
1       Sun
2       Sun
3       Sun
4       Sun
       ...
239     Sat
240     Sat
241     Sat
242     Sat
243    Thur
Name: day, Length: 244, dtype: object